# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Create Nuget Sdl.MultiSelectCombo'
  inputs:
    command: pack
    packagesToPack: MultiSelectComboBox/MultiSelectComboBoxSdl/Sdl.MultiSelectComboBox.csproj
    configuration: Release
    versioningScheme: byBuildNumber
    buildProperties: 'id=Sdl.MultiSelectCombo.Release;name=Sdl.MultiSelectCombo.Release;'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
